DROP TABLE IF EXISTS employee;

CREATE TABLE employee(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_Name VARCHAR(250) NOT NULL,
  last_Name VARCHAR(250) NOT NULL,
  address VARCHAR(250) DEFAULT NULL
);