server:
  port: 9098    #port number
 
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: ${HOST_NAME:localhost}
    
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:
  application:
    name: wissen-service   #service name

 
logging:
  level:
    com.example.howtodoinjava: DEBUG